### ISSUE TITLE
RoomId to room name

### ISSUE THREAD

**Issue by DevinR528** [matrix-org/matrix-rust-sdk#1]
Great crate! It's good to see a rust-skd.

I am messing around with a matrix command line client and have the login functionality down but have hit a bit of an issue with the `RoomId` to room name or alias mapping.

I found the coresponding js code [here](https://github.com/matrix-org/matrix-js-sdk/blob/33941eb37bffe41958ba9887fc8070dfb1a0ee76/src/models/room.js#L1823) but am unsure how exactly to duplicate this, [here](https://github.com/DevinR528/RumaTui/blob/master/src/client/mod.rs#L120-L203) is my attempt.

I would love to help out if there is anything I could do, I realize it's early days.

**Comment by poljar** [comment]
The client will create `Room` structs for you, or you can create those yourself if you want to pursue a lockless design with regards to the room state.

This [room struct](https://github.com/matrix-org/matrix-rust-sdk/blob/master/src/base_client.rs#L52) receives all the room timeline/state events and modifies it's state accordingly.

It only handles member events for now, but other events should eventually be handled as well. After the room naming events are handled and the state in the struct is accordingly modified a method that calculates the room name can be added.

It is quite early but handling rooms is something I won't touch for a while since I'm focused on the crypto support, so this could be worked on without any clashes if you're interested.

PS: The Rust port of weechat-matrix is using this crate as well, it may showcase how to use stuff as well, besides the login example in the repo: https://github.com/poljar/weechat-matrix-rs/blob/master/src/server.rs#L557

**Comment by DevinR528** [comment]
Thanks for the quick and detailed response! I'll start something going in a day or two.

**Comment by poljar** [comment]
This has been closed by #2 and #4.
