### ISSUE TITLE
Error when building Swift FFI

### ISSUE THREAD

**Issue by juliettebee** [matrix-org/matrix-rust-sdk#1101]
I'm trying to build the Swift FFI with `sh build_xcframework.sh` but I'm getting `Error: invalid value: integer '3', expected variant index 0 <= i < 2`, how do I fix?

**Comment by jplatte** [comment]
Currently, you will have to install `uniffi-bindgen` from their git repository, because we're improving UniFFI alongside our own bindings and want to use the latest features as soon as they are available. In the current state, this would be `cargo install --git https://github.com/mozilla/uniffi-rs --rev 0eee77f67b716c4896494606e5931d249871b23a`.

When pulling a new version of the SDK repo, check [`bindings/matrix-sdk-ffi/Cargo.toml`])https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/Cargo.toml#L37) for the right git rev to use.
