### ISSUE TITLE
Remove the possibility of an undecryptable local echo from the timeline data model

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#1175]
… since it's a non-sensical combination.

**Comment by poljar** [comment]
Turns out, in the older rooms where the algorithm is set to `m.olm.*` it is common to get a undecryptable event you sent yourself.

In that case we should take the event id and whatnot from the remote echo and update the local echo with it.

**Comment by bnjbvr** [comment]
> Turns out, in the older rooms where the algorithm is set to m.olm.* it is common to get a undecryptable event you sent yourself.

… that you sent yourself, from the same device/session, or from a different one?

In general: i am not sure what this issue entails, since the action of adding a timeline item involves an `AnySyncTimelineEvent`, which can be… anything, really, including a `m.room.encrypted` event. Is this issue proposing that we have specialized timeline actions, that take more specific types? (e.g. `AddMessage` would take an `AnyRoomMessageLikeEvent`, etc.)

**Comment by poljar** [comment]
I think it was about the local echo, when it gets replaced with the remote echo, that there shouldn't be an enum variant where the remote echo can't be decrypted.

But the `m.olm.*` algorithms, granted which we don't support, function exactly like that.

In the `m.olm.*` world you never encrypt the event for your own device, so anything the server returns as the remote echo will never be decryptable.

So in this case, you would need to combine the local echo with the metadata from the remote echo to build an `AnySyncTimelineEvent` instead of just attempting to decrypt the remote echo like we do now.

**Comment by jplatte** [comment]
No, this was for local echo timeline items directly, not when they transition to a remote (echoed) event. Currently, like back when this issue was created, [`EventTimelineItem`](https://github.com/matrix-org/matrix-rust-sdk/blob/965a59d5b80693ab4ec2735cd6115472b1d5bb13/crates/matrix-sdk-ui/src/timeline/event_item/mod.rs#L68) contains a `content` field that has an `UnableToDecrypt` variant, regardless of whether it is a local echo or not. The content would have to move into the `kind` in one way or another to fix this. But really, I doubt it's worth the effort. I originally created this issue because you (poljar) were saying that this being possible in the data model is a bit inelegant.

**Comment by bnjbvr** [comment]
Thanks for chiming in @jplatte; agreed this is likely not worth it.
