### ISSUE TITLE
Empty rooms get an empty string as the display name

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#133]

**Comment by jsparber** [comment]
this is also the case for invited Rooms.

**Comment by Austin-Ray** [comment]
Hi @poljar, is this an active issue? If so, what's the expected value?

**Comment by poljar** [comment]
I think the expected value is `Empty room` or `Empty room (was _the name of the member that left_)`

**Comment by Austin-Ray** [comment]
Thanks, I'll start work on this.

**Comment by jsparber** [comment]
The last fix didn't fully fix the issue. Invites to DMs are now considered as `Empty rooms`, after joining [display_name()]( https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/room/enum.Room.html#method.display_name) returns the correct name.

**Comment by poljar** [comment]
Do you mean now as in after the PR was merged or was it that way before the PR as well?

**Comment by jsparber** [comment]
Now as in after #241. The issue is not only for DMs but for all invited rooms.

**Comment by Austin-Ray** [comment]
I'll investigate why that regression appeared and setup a unit test catch it. Apologies for the error in my PR.

**Comment by Austin-Ray** [comment]
I've been debugging the invited room issue and have hit a bit of a wall (it's also late on my end.) Here's where I'm currently at:

I've extended the `invited_room` unit test to verify `name` and `display_name` (and have a reproducible failure). It's simple and the code is viewable at https://github.com/Austin-Ray/matrix-rust-sdk/commit/26df14bb8cdb8528baaf061a4966cdfaac8caff6. 

The confounding part is the `name` check fails with `None`, but the sync json used by the test includes a `m.room.name` event https://github.com/matrix-org/matrix-rust-sdk/blob/7a5daf6ac73771bed88609922d4f920eb6db3785/matrix_sdk_test/src/test_json/sync.rs#L735-L741

but I'm able to follow that event all the way down to

 https://github.com/matrix-org/matrix-rust-sdk/blob/7a5daf6ac73771bed88609922d4f920eb6db3785/matrix_sdk_base/src/rooms/mod.rs#L85-L88

where it updates the value of name, but calling `name()` still returns `None`

So the root cause seems to be that the invited rooms don't have a name for use in `display_name()`. However, I'm still familiarizing myself with the codebase and might have gotten tripped up.

Any suggests for how to proceed?

**Comment by poljar** [comment]
The problem was that the room info was updated but when it had to be swapped out for the updated one it never was, since it was in the bucket for stripped room infos; #248 fixes this, not sure if the room names are completely correct now, considering that invited rooms always lack a room summary.

**Comment by poljar** [comment]
Another thing, this doesn't seem to be a regression due to #241.

**Comment by Austin-Ray** [comment]
> not sure if the room names are completely correct now, considering that invited rooms always lack a room summary.

The naming algorithm[0] says:

> Clients should consider m.room.member events for users other than the logged-in user, as defined below.

So it looks like a summary isn't needed for invited rooms. I'll work on a test case to verify if the existing implementation does that. Are there any conventions for modifying `matrix_sdk_test/src/test_json/sync.rs`?

[0] https://matrix.org/docs/spec/client_server/latest#calculating-the-display-name-for-a-room

**Comment by poljar** [comment]
Yeah I know that stuff should work without a summary, though not sure if it does work.

No real conventions, in the worst case you can just add another room, that way you won't break existing tests.

**Comment by Austin-Ray** [comment]
Would you prefer creating a `RoomSummary` from the `m.room.member` events or should `calculate_name()` have a different control flow to invited rooms?

**Comment by poljar** [comment]
I think the whole thing should work without a summary considering that servers might not provide one.
