### ISSUE TITLE
Allow explicit destruction of OlmMachine in Node.JS bindings 

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-rust-sdk#1379]
In practice, we've noticed that dropping a OlmMachine in Node.JS and then recreating it with the same parameters leads to crashes (https://github.com/matrix-org/matrix-hookshot/issues/609) where the Sled DB is still locked from it's previous use. We'd like a way to explicitly clean up resources on an OlmMachine before reusing it.

**Comment by Hywan** [comment]
Solved in #1400.

**Comment by poljar** [comment]
I don't think that this can reliably solve your problem. Mainly because the store, AKA sled, is shared with a lot more objects than just the `OlmMachine`.

Any type of identity you pull out of the store will hold on to a reference of the store. So we'll need explicit destructors for this as well.

The correct solution is to stop using the sled store, you will need to pursue this anyways because the sled store:

a) Is getting deprecated
b) Is not designed for the massive deployments an app-service tries to support

**Comment by Hywan** [comment]
@Half-Shot would https://github.com/matrix-org/matrix-rust-sdk/pull/1400 help?

**Comment by poljar** [comment]
So we now have the SQLite based cryptostore, the SQLite based one will become the default one soon. The SQLite store can be opened multiple times, which makes #1400 obsolete.

**Comment by Half-Shot** [comment]
Agree'd, let's do that. https://github.com/matrix-org/matrix-rust-sdk/issues/1461
