### ISSUE TITLE
Decrypt messages from room::Common::messages()

### ISSUE THREAD

**Issue by VanillaBrooks** [matrix-org/matrix-rust-sdk#189]
I'm looking for an easy way to use the internal client state `OlmMachine`so that I can decrypt a set of message that I'm getting from `get_message_events::Response` (of which room::Common::messages() is a [wrapper](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/src/room/common.rs#L94-L100)). Unless I'm missing something, I don't see a method to decrypt the `MessageEvent<EncryptedEventContent>` that comes from `AnyMessageEvent::RoomEncrypted`. 

I'm considering adding a method similar to [`decrypt_room_event`](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk_crypto/src/machine.rs#L921-L929) (that takes a `EncryptedEventContent`) on `OlmMachine`. The `OlmMachine` would then be accessed through `Deref`  on `matrix_sdk::Client` ->  `BaseClient` ->  `olm_machine()` or some higher level method. Is this the best way forward or does something like this already exist?

I am using the master branch.

**Comment by poljar** [comment]
`MessageEvent<EncryptedEventContent>` can be turned into a `SyncMessageEvent<EncryptedEventContent` easily, it has a [`From`](https://docs.rs/ruma-events/0.22.0-alpha.2/ruma_events/struct.MessageEvent.html#impl-From%3CMessageEvent%3CC%3E%3E) implementation.

Though we might want to add a helper method that does that for you.

I'd rather we add a separate method on the `Client` instead of using `Deref` for so many levels of indirection.

Finally, we do want to transparently decrypt the `get_message_events::Response` for the user, so we only need to expose such methods when the user wants to retry decryption.

**Comment by poljar** [comment]
You can access the `OlmMachine` from the `BaseClient` using [this](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_base/struct.BaseClient.html#method.olm_machine) method and `Client` holds the `BaseClient`.

The `OlmMachine` and `BaseClient` have a lot of relatively complex methods which I'd rather not expose through the `Client`, exposing it would increase the API surface considerably and yet most of those methods should never be used by end users of the `Client`.

**Comment by jsparber** [comment]
I think this should be resolved via https://github.com/matrix-org/matrix-rust-sdk/issues/178

**Comment by VanillaBrooks** [comment]
That does look like it would resolve this issue. I will work on that If find the time. For now I have solved the issue by using the above mentioned `From` implementation combined with  the `BaseClient::olm_machine()` method (and forking to impl `Deref` for `Client`)
