### ISSUE TITLE
Implement UnifiedPush for battery savings

### ISSUE THREAD

**Issue by okias** [matrix-org/matrix-rust-sdk#1956]
[UnifiedPush](https://unifiedpush.org/) support is essential to prolong battery life on mobile phones.

This was a originally issue against [Fractal](https://gitlab.gnome.org/GNOME/fractal/-/issues/675#note_1752387), but since Fractal now does use `matrix-rust-sdk`, moving here.

**Comment by Hywan** [comment]
The Rust SDK doesn't “connect” to the OS notification API. This is more something for the SDK consumers rather than us. Except if I've misunderstood what you're proposing here.

**Comment by afranke** [comment]
My bad, I initially misunderstood the role of UnifiedPush. I basically thought the “notifications” it handled would be lower level, rather than “Matrix notifications”, and that it would serve as a way pause syncing if there is no need to, regardless of the user getting Matrix-notifications.  I can see now that I assumed incorrectly. I’ll reopen the downstream issue, feel free to close this one.

**Comment by poljar** [comment]
Thanks, if there is indeed something the SDK should do here, please re-open.
