### ISSUE TITLE
Sometimes `Room::display_name()` returns the calculated name even if name is available

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#1980]
The `display_name()` function used inside the `NotificationItem` seems to be returning sometimes the calculated name instead of the inner name that Room has.

The issue has been seen on both Android and iOS where sometimes the notification displays the name using the room members, even if a set name for the room exists, and should also be in the store.

https://github.com/matrix-org/matrix-rust-sdk/blob/ce9a079882031bec189819f4c9e27c1cbf57cdfa/crates/matrix-sdk-base/src/rooms/normal.rs#L314-L316

**Comment by manuroe** [comment]
This gives weird notifications display like:

![IMG_6695](https://github.com/matrix-org/matrix-rust-sdk/assets/8418515/90f4916b-c2c3-4aab-a1ab-2897ee9bc3b7)

Note the room avatar is correct.

**Comment by Hywan** [comment]
As we can read here: https://github.com/matrix-org/matrix-rust-sdk/blob/ce9a079882031bec189819f4c9e27c1cbf57cdfa/crates/matrix-sdk-base/src/rooms/normal.rs#L371-L383

If the `BaseRoomInfo` contains a name (returned by `inner.name()`, it's directly used as a `DisplayName::Named`. Otherwise, if we have a canonical alias, it's directly used as a `DisplayName::Aliased`.

This is done before doing a real “calculation” for the room name. So it means that the room may not have a name internally if it's calculated.

It's possible that Sliding Sync doesn't send the room name. Actually, the proxy/server is likely to send the name only once per session, when the room appears for the first time during a sync.

Do you know if this is reproducible? What led to this situation?

**Comment by poljar** [comment]
> It's possible that Sliding Sync doesn't send the room name. Actually, the proxy/server is likely to send the name only once per session, when the room appears for the first time during a sync. Also, if the proxy/server sends a name for the room, it overwrites the previous name:

Do note, that the proxy sends the result of the calculation, and not an `m.room.name`. We should likely store the result of the calculation the SS proxy gives us in the `BaseRoomInfo` as well. Which likely will fix this bug as well since I suspect that the problem is that we just never receive an `m.room.name` event.

**Comment by manuroe** [comment]
How can we explain the room name is correctly displayed within the app (2nd screenshot [here](https://github.com/matrix-org/matrix-rust-sdk/issues/1980#issuecomment-1564479701)) if the SS proxy does not send the `m.room.name` event? 

Related question: why can we have the `m.room.avatar` event but not the `m.room.name` event?

**Comment by gnunicorn** [comment]
Indeed sliding sync (by default) doesn't sent the `m.room.name` event bur only a calculated name. And though that calculation updates the internal SlidingSyncRoom data, that info is not passed down to the base-info/regular room type. If you only use sliding sync to sync and then directly query the db for the room object, the room name is empty.

**Comment by Velin92** [comment]
I have released this on current nightly, I have never experienced this issue so far (but my personal account does not have a lot of group rooms, mostly DMs), let's see if is not reported anymore by those who experienced it like @manuroe

**Comment by manuroe** [comment]
thanks @andybalaam for the fix. After few more testing, it works in a sense that if the app/sdk knows the room, like when the room got displayed in the room list, the display name is correctly displayed in the notification. We have now a consistent behavior between the app and the extension.
But if we receive a notification for a room the app never have not met yet, the room name will be still wrong in the notification. But this is orthogonal to this issue and it will be fixed it in the better notification management we are doing.
