### ISSUE TITLE
Sliding Sync: Avoid having out-of-sync between `room_list_entry` and `rooms`

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#1996]
In https://github.com/matrix-org/matrix-rust-sdk/pull/1995, I'm raising a possible bug.

Imagine the following Sliding Sync response:

```json
{
    "pos": "…",
    "lists": {
        "…": {
            "count": "…",
            "ops": [
                {
                    "op": "INSERT",
                    "index": 0,
                    "room_id": "!foo:bar.org",
                }
            ]
        }
    },
    "rooms": []
}
```

The `SlidingSyncListInner::room_list` (aka the room list entry of this list) will be updated based on what is inside `lists.….ops`… but `SlidingSync::rooms` won't be updated because `rooms` is empty — or at least, `!foo:bar.org` is missing! Thus, from the room list entry stream, a user can receive an update: “a new room is here”, but it's actually not present. This reminds me this bug: https://github.com/vector-im/element-x-ios/issues/874. I'm not saying it's the cause of this bug, it's very likely to be something different, but the “behavior” from the user point of view might be the same: A room appears in the room list, but it's inactive because the `SlidingSyncRoom` doesn't exist.

What to do:

1. Either we test that all the `lists.*.ops` map to something relevant inside `rooms` (tricky),
2. Or we make sure that the SS API is robust against this situation. So far, `SlidingSync::get_room` returns an `Option`, which is perfect to detect this kind of situation.

Should we do more? I'm asking the question.

**Comment by bnjbvr** [comment]
Thanks for opening an issue. It seems tricky to have client validate the response's data, because we could have situations where the returned data is partially valid — e.g. a list's ops contain `INSERT @ 0` for a non-existing room, and then `INSERT 1 for another room existing in the rooms list; what do we do in this case? I wonder if we should discard the result entirely, and wait for the server to send us updated, complete data.

Would the situation you're describing only happen if the server is sending us incomplete data (which in that case would be a bug in the server), or are there legitimate cases where the server would send such incomplete data?

**Comment by Hywan** [comment]
It can happen only if the response is invalid, so bug in the server, or a malicious response?

**Comment by Hywan** [comment]
Let's close this issue as we are going to ignore sync ops soon, and rely only on `rooms`.
