### ISSUE TITLE
Change the store traits so they expose a transactional API

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#2000]
This would increase robustness in the case of the two sync loops, so that we're sure that there aren't any partial write to the db that the main loop consumer would try to read later.

**Comment by poljar** [comment]
To explain a bit further, since we do use transactions for all of our writes.

Currently all the changes we want to write are first collected into a struct named `Changes`. Then we call `Store.save_changes()` which saves everything we collected in a single transaction.

This was mostly done since sled has an API where you pass in a closure which gets executed as part of a transaction. In this closure you write your values to the db and everybody is happy.

But most other databases have a `Database::get_transaction(&self) -> &Transaction` interface. Crucially `SQLite` and `IndexedDB` behave this way.

We could change our store traits to reflect this new reality and get rid of the `Store::save_changes(&self, changes: Changes)` API and add a `Store::get_transaction(&self)` API instead.

This way, if we need to do reads during a write, they also become part of the transaction.

**Comment by bnjbvr** [comment]
Wait, turns out that sqlite implementations for both the crypto store trait and the state store trait make use of sqlite transactions. So it's a non issue, as it's already implemented, or are you suggesting something else?

**Comment by poljar** [comment]
I am.

If you take a look at the `CryptoStore` trait:

https://github.com/matrix-org/matrix-rust-sdk/blob/d6d19d9111864b1ce316917dc795da6da222d96a/crates/matrix-sdk-crypto/src/store/traits.rs#L59

We have this method, which may or may not open a transaction behind the scenes, our current implementations do so.

But we also have some other methods:

https://github.com/matrix-org/matrix-rust-sdk/blob/d6d19d9111864b1ce316917dc795da6da222d96a/crates/matrix-sdk-crypto/src/store/traits.rs#L219-L228

Currently we can't store two custom values in a single transaction. Any reads that may happen before a `save_changes()` call also aren't part of the transaction which the `save_changes()` method will use.

If we instead have a method in the `CryptoStore` trait which returns a transaction, and then the transaction object exposes a `set_custom_value()` method, then we could store multiple values in a single transaction.

That being said, none of this is required currently, and the faux transaction using `save_changes()` will work just fine.

The above change to our store traits has been previously suggested by @jplatte, so he may have even more concrete ideas.

**Comment by richvdh** [comment]
> This was mostly done since sled has an API where you pass in a closure which gets executed as part of a transaction. In this closure you write your values to the db and everybody is happy.
>
> But most other databases have a Database::get_transaction(&self) -> &Transaction interface. Crucially SQLite and IndexedDB behave this way.

You have to be careful with IndexedDB transactions: in particular you can't keep them open indefinitely; they will terminate as soon as you stop giving them work to do, so you can't do any `async` operations. That may be fine here, but it's a footgun that needs bearing in mind.

**Comment by richvdh** [comment]
We no longer believe this approach is correct.
