### ISSUE TITLE
Use well_known infromation from login response

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#219]
**Is your feature request related to a problem? Please describe.**
The developer can't implement well_known support without creating a new `Client` after login since the `homeserver` url can't be changed.

**Describe the solution you'd like**
Make the sdk update it's own `homeserver` url according to the [`well_known`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/api/r0/session/login/struct.Response.html#structfield.well_known) response.

**Describe alternatives you've considered**
Make the `homserver` url mutable and allow the developer to change it.

**Comment by timorl** [comment]
So I started looking into that and I'm a bit stuck as far as the design goes. I think what we want is that `HttpClient` checks `well_known` before making any other API calls and updates its own homeserver URL if the response is valid. I can see about three ways this could be done:

1. Check `well_known` the first time `send` is called. Pros: the user expects to wait on some http requests anyway, one more shouldn't be a problem. Cons: this mutates `HttpClient`, so now all calls to `send` have to take a mutable reference to `self`, which cascades to mutable references to `Client`, which significantly changes the API of the whole thing.
2. Check `well_known` when creating `HttpServer`. Pros: `HttpServer` can still be  constant for all of its existence. Cons: `HttpServer` now has an async constructor which performs HTTP operations. I'm not actually sure how problematic that is, but at least it seems strange.
3. Have an explicit method that checks `well_known` and updates the URL. Pros: only this method has to mutate `HttpClient` and `Client`, so no changes to the current API. Cons: literally all the users of the library will initially miss that they have to do this explicitly and we will end up with a lot of apps that handle `well_known` wrong in the ecosystem.

Personally I like 2. > 1. >>> 3., but all have problems and I might not have enough Rust knowledge to judge them properly. Any preferences or better propositions?

**Comment by jplatte** [comment]
+1 for option 2.

**Comment by poljar** [comment]
Correct me if I'm wrong but I think the well_known discovery works a bit differently, it works in two ways:

1. If a user logs in, the login response may contain `well_known` information which should be used to reconfigure the client
2. If someone wants to discover the server from a `user_id`, they should hit up `https://$user_id_server_part/.well-known/matrix/client` and check the homeserver URL

As per subject, I believe this issue is about 1, but we can expand it to contain both things.

> literally all the users of the library will initially miss that they have to do this explicitly and we will end up with a lot of apps that handle well_known wrong in the ecosystem.

Users will have to login, and if we reconfigure the client at login time, nobody will have the chance to miss this. Of course now we need to either store the new homeserver URL, or the `restore_login()` method would need to do well-known lookups. I think storing the URL makes sense?

As for doing the lookup before one is logged in, or in other words creating a `Client` object with only a `user_id` a separate async constructor that does a `well-known` lookup should work, no?

And finally, it may make sense to have the ability to disable well-known lookup upon logging in, e.g. if you configure your client to go through `mitmproxy` in reverse proxy mode, and the server returns well-known information, your client will sidestep `mitmproxy` and you would be forced to use something like [this](https://github.com/matrix-org/matrix-rust-sdk/blob/master/contrib/mitmproxy/well-known-block.py).

**Comment by timorl** [comment]
Oh, sorry about the confusion then, I wasn't aware of 1. at all so I assumed this was all about 2. I have a version based on my understanding almost ready, just fighting with mockito to get proper tests working, but I think it might be wrong – I hope y'all will be able to tell me what I should change.

**Comment by zecakeh** [comment]
This issue was closed but if I understand it correctly, only `2.` was addressed in #233, not `1.`

**Comment by poljar** [comment]
Yeah, that's correct.
