### ISSUE TITLE
State not updated when testing with HTTP mocks rather than `base_client.receive_sync_response`

### ISSUE THREAD

**Issue by ahal** [matrix-org/matrix-rust-sdk#224]
This is a follow up to https://github.com/matrix-org/matrix-rust-sdk/pull/214/commits/a1c0acbd0c9d5047b2aef293f86770a79b46c8e0 and issue #208 

The solution outlined in https://github.com/matrix-org/matrix-rust-sdk/issues/208#issuecomment-823292426 has mostly been working well. However I noticed that `base_config.receive_sync_response` is responsible for setting store state. So when using `EventBuilder.build_json_sync_response` with an HTTP mock, assertions that query the store will fail.

I don't really have any ideas here given your desire to avoid a shim, so I understand if this issue gets closed. In that case I'll just be careful about what assertions I make. Figured it was at least worth filing though.

**Comment by poljar** [comment]
I think this was discussed somewhere before, to get any room info beside the ID you'll need to wait for the sync response. We could start returning an empty room object but the usefulness of doing so might be limited considering that you won't have the name/members/any other state. 

It's also a bit tricky to make this work in a safe way, since it might break E2EE if you start sending messages before the client knows that the room is encrypted.

If this is only needed for tests I suggest you to build another sync response which marks the room as joined.

PS: The example is technically correct since you get another sync after the join, which would move the room back to the invited state.

**Comment by ahal** [comment]
Setting the room joined in the sync response would defeat the purpose of the test (that autojoin is working). But thinking about it, I guess asserting that the join mock is called in the first place is good enough to cover that. So feel free to close this if you think there isn't anything else to be done here.

**Comment by poljar** [comment]
Yeah, that's another way to test this. Closing now.
