### ISSUE TITLE
Workaround for missing `limited` implementation in SS proxy

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#2261]
If the proxy cannot implement the [limited flag](https://github.com/matrix-org/sliding-sync/issues/197) in the coming weeks, we need to implement a workaround because it creates an high priority bug on the client side where [blocks of messages are missing in the timeline](https://github.com/vector-im/element-x-ios/issues/1197).

The suggested workaround is:
*Implementing the limited flag requires delta tokens support, and can be almost completely emulated by checking if you know `timeline[0].event_id`*
([internal discussion](https://matrix.to/#/!kCCQTCfnABLKGGvQjo:matrix.org/$wbzZOr4pLoGwlJjm2RYgfuYljqRMRJjuzn8uigvjHag?via=matrix.org&via=element.io&via=one.ems.host))

**Comment by poljar** [comment]
As it turns out. SS will might you duplicate events in the case the `initial` flag is set in the room:

```json
{
  "rooms": {
    "!foo:bar": {
      "name": "The calculated room name",
      // Flag which is set when this is the first time the server is sending this data on this connection.
      "initial": true,
     ....
}
```

In the case of `initial` being true two things can happen:
1. We might receive events we have already seen and cached in the timeline
2. We might see a completely new set of events.

In the case of a new set of events, a gap might exists and a reload of the timeline is necessary.
