### ISSUE TITLE
Ignoring/Unignoring a user does not trigger a timeline refresh/reset

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#2284]
Before ignoring or unignoring a user triggered a reset in the timeline to filter out (or reinsert) messages from that blocked user.
It will prevent new messages from being inserted in the timeline from the ignore user (or viceversa make new messages appear if is unignored) but will not handle previous existing ones.
 
An app reboot on Element X is required to restore the state of the user.

https://github.com/vector-im/element-x-ios/issues/911

**Comment by kittykat** [comment]
Also related: vector-im/element-x-ios/issues/910

**Comment by Hywan** [comment]
I've another bug:

* Ignoring a member
* Closing the app
* Opening the app
* The message of the ignored member still appears, but at the top of the timeline.

**Comment by Hywan** [comment]
It has stopped working because the code you wrote in https://github.com/matrix-org/matrix-rust-sdk/pull/1705/ has been removed when SlidingSync bindings have been removed in https://github.com/matrix-org/matrix-rust-sdk/pull/2222. That's the problem when bindings do more stuff than just bindings ;-).

Working on it.
