### ISSUE TITLE
`latest_event()` does not return local echo, but only remote messages

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#2303]
This is related to: https://github.com/vector-im/element-x-ios/issues/1294

**Comment by jplatte** [comment]
Hm, this is an interesting one. The current data model and the fact that the latest event is stored in the `RoomInfo` means that we can't really store local echoes (since those are entirely ephemeral as far as the `matrix-sdk` / `matrix-sdk-base` crates are concerned).

**Comment by Hywan** [comment]
Yeah. Either that's something the app/user should handle, _or_ `SlidingSyncRoomExt::latest_timeline_item` should handle that.

An alternative is for the app to display “Sending…” with a particular text style, instead of showing the latest event? It conveys that something is being sent, and we don't have to add this complexity in the SDK :-p?

**Comment by jplatte** [comment]
Actually I disagree, we could have `RoomListEntry::latest_event` that has access to the timeline and only calls `latest_event` on the sliding sync room if there is no applicable local echo in the timeline. But that's only a very vague description of how it could work, details would have to be figured out.

**Comment by jplatte** [comment]
Er, I wanted to write `RoomListEntry::latest_event`. Edited.
