### ISSUE TITLE
Sync with a sync token from previous sync

### ISSUE THREAD

**Issue by FlixCoder** [matrix-org/matrix-rust-sdk#2423]
Hi,

I noticed that `client.sync_once(..)` includes in the documentation how to use the sync_token of the previous sync. However, this is not possible to do like that (anymore) and I am unsure whether it is possible to do at all.

```rust
let sync_response = client.sync_once(SyncSettings::default()).await?;
```
The `sync_response` does not include a public `next_batch` anymore. Is there a new way to go about this? How should the documentation be updated?

Thanks!

**Comment by bnjbvr** [comment]
Hi! It does, but sometimes on my IDE rust-analyzer seems to not find it (it seems to be confused about the response type). See some example usage (on `main` this compiles, at the very least):

```rust
      let response = client.sync_once(SyncSettings::default()).await?;
      let settings = SyncSettings::default().token(response.next_batch);
      let next_response = client.sync_once(settings).await?; // and so on
```

Does this clarify your issue? If the doc is out of sync, please feel free to make a PR to update it!

**Comment by jplatte** [comment]
This is a somewhat long-standing issue. The `next_batch` accessor was removed because we wanted to make the public API less specific to the current syncing mechanism in anticipation for sliding sync. I also think it's very confusing that `sync` and `sync_once` use different defaults for the token. Maybe we should just change `sync_once` to default to using the stored token as well 🤔

I think it will take a little while to get this resolved unfortunately, but thanks for opening the issue. As a workaround, I think it should work to use [`sync_with_result_callback`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.Client.html#method.sync_with_result_callback) which should also default to using the stored token, and returning `Ok(LoopCtrl::Break)` from the closure you have to provide unconditionally.

**Comment by FlixCoder** [comment]
> rust-analyzer seems to not find it

you are right, it actually just seems to be rust-analyzer, sorry 😅 

> Maybe we should just change sync_once to default to using the stored token as well 🤔

I would welcome that, especially, now that I noticed it is causing bugs: https://github.com/matrix-org/matrix-rust-sdk/issues/2424#issuecomment-1686029342
Seems to be buggy or a footgun.

> As a workaround, I think it should work to use [sync_with_result_callback](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.Client.html#method.sync_with_result_callback) which should also default to using the stored token, and returning Ok(LoopCtrl::Break) from the closure you have to provide unconditionally.

Thanks!

Now since the initial point was actually wrong, should this issue be closed or do you want to keep it for the `sync_once` token usage problem?

**Comment by jplatte** [comment]
Closing in favor of #1835.
