### ISSUE TITLE
Make `Account::decrypt_to_device_event` abstract over the encryption scheme

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-sdk#256]
`olm/account.rs` has the following line:

https://github.com/matrix-org/matrix-rust-sdk/blob/0df782e93ee2d9d9c338775adbe2cf1b35048740/matrix_sdk_crypto/src/olm/account.rs#L128-L134

While there is already another encryption scheme, and it's possible in the future there will be more;

```rs
#[cfg(non_exhaustive)]
pub enum EncryptedEventScheme {
    /// An event encrypted with *m.olm.v1.curve25519-aes-sha2*.
    #[serde(rename = "m.olm.v1.curve25519-aes-sha2")]
    OlmV1Curve25519AesSha2(OlmV1Curve25519AesSha2Content),

    /// An event encrypted with *m.megolm.v1.aes-sha2*.
    #[serde(rename = "m.megolm.v1.aes-sha2")]
    MegolmV1AesSha2(MegolmV1AesSha2Content),
}
```

Maybe it's possible to make a trait for each of those, which gets called depending on the scheme of the encrypted event? This'll reduce the non-locality of this sort of code, because here `decrypt_to_device_event` is only assuming one type of encryption exists, while there may be more in the future.

**Comment by poljar** [comment]
`m.olm.*` is tied to an account while `m.megolm` is not, that's why the megolm variant isn't handled here but in another subsystem, another important thing is that megolm requires a `room_id` and thus can't be sent over to-device messaging.

If there is a new `m.olm.*` variant we'll probably just have different `Session` types which perform a slightly modified 3DH handshake and perhaps use some other symmetric primitives, this would mean that we'll have another `Session` variant and the `Account` would just pick the appropriate `Session` variant depending on the algorithm.

If there is a completely different scheme, e.g. MLS, we'll likely introduce a separate subsystem.

It doesn't seem wise to introduce additional complexity and indirection here using some type of trait setup considering the above, I'm well aware that other SDKs do abstract stuff away behind an abstract `Decryptor` type but such a setup is yet to bear fruit.

**Comment by ShadowJonathan** [comment]
🤔 Hmmm, good point, I'll have to properly look at how the library handles other encryption-related behavior, my concern was mostly for public-facing API, which I'm going to guess is not the case here.

**Comment by poljar** [comment]
No that isn't public facing, the whole to-device decryption is hidden from users. The only public method we have for decryption is for `m.megolm.*` events over [here](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_crypto/struct.OlmMachine.html#method.decrypt_room_event).
