### ISSUE TITLE
Room List API: Expose an indicator when the user has been mentioned in a room

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#2607]
Update the Room List API to achieve https://github.com/vector-im/element-meta/issues/2064

**Comment by jplatte** [comment]
We don't really need to do anything to support *reading* intentional mentions, that's already handled by Ruma and the push rules should take care of the regular username scanning being skipped. However, before we implement any additional indicators in the room list, we have to implement a better mark-room-read logic, otherwise we will get similar bugs as element web where it is very common to get rooms stuck in an unread state.

**Comment by Velin92** [comment]
Kamino cloned this issue to [matrix-org/matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/issues/2954)

**Comment by bnjbvr** [comment]
This is available through the `RoomInfo`. It's not reflected in real-time because the Room List API doesn't automatically update whenever the `RoomInfo` is updated, but that's a separate issue. Calling this done, unless something else is missing.
