### ISSUE TITLE
Offer highlevel guarantees for "client.join_room_by_id_or_alias" and companions

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-rust-sdk#267]
**Is your feature request related to a problem? Please describe.**
Currently the sdk doesnt give you any guarantees that a room joined via [`client.join_room_by_id_or_alias`](https://github.com/matrix-org/matrix-rust-sdk/blob/1a5cd544e7e6e5cf3231e8ce44a34d2dab18e02d/matrix_sdk/src/client.rs#L1479) will show up in [`client.get_joined_room`](https://github.com/matrix-org/matrix-rust-sdk/blob/1a5cd544e7e6e5cf3231e8ce44a34d2dab18e02d/matrix_sdk/src/client.rs#L933) after completion of the future as the join function only give guarantees for the HTTP call.

For example at this time to ensure that `get_joined_room` returns a room of type `Joined` the user has to either wait for sync completion via a sleep (bad as it is based on assumptions and easily breaks) or by having it handled using the event emitter. which however causes weird functions to be needed. (For example channels to be able to return the Room in the function which is used for joining), An alternative way is doing something like this which requires however that the user modifies the sdk currently:

```rust
 warn!("Room {} was not in the get_joined_room() response. Going to create a fake room for now...",room_alias);
// We need to fake a room for now
let mut base_room = client
    .store()
    .get_or_create_room(&resp.room_id, RoomType::Joined)
    .await;

if let RoomType::Invited = base_room.room_type() {
     info!(
         "Fallback room created with type {:?} instead of Joined. Correcting...",
         base_room.room_type()
    );
    base_room.mark_as_joined();
} else if let RoomType::Left = base_room.room_type() {
    info!(
        "Fallback room created with type {:?} instead of Joined. Correcting...",
        base_room.room_type()
    );
    base_room.mark_as_joined();
}
return Joined::new(client.clone(), base_room);
```

This can be considered save as according to spec a response of type 200 on the join endpoint means a successful join.

**Describe the solution you'd like**
There are 2 possible solutions @johannescpk and I saw:

1. Block until we get the membership event and eventually timeout to prevent deadlocks. This is equivalent to the first workaround above and would ensure having a full joined room. However this will break for services like t2bot which doesnt echo joins of the own user for appservices ( https://github.com/t2bot/synapse/commit/dd3e1401a3154ca17f12c041a1a932907dadc3c6#diff-ec5620287b555c273e59f2c5675f85f82059083b1d9b76d7f413c807790e81fbR259-R261 ). Those would never succeed with this method.

2. An better alternative would be introduce a "StrippedJoinedRoom" which only guarantees the existence of a room_id. In certain situation it is a usecase to only need to know room_id + "am i joined". This is the case for server_stats where I need to pass rooms of type "Joined" due to that being the type EventEmitter returns for messages. I only need the room id from it at that point in time. As soon as we get a sync or the data as an appservice (like members and other state that the current "Joined" guarantees) the room would in the state store get upgraded to a regular full featured room of type "Joined". This solution would work with patches like the one t2bot relies upon.

**Why a StrippedJoinedRoom?**

This is mainly as "Joined" gives us some other guarantees already which we cant give with just having a room_id. For example https://github.com/matrix-org/matrix-rust-sdk/blob/ef6e481860d9b6028efb51cfff2a6850b0ced502/matrix_sdk/src/room/joined.rs#L287-L297 cant be guaranteed anymore and instead something like https://github.com/matrix-org/matrix-rust-sdk/blob/ef6e481860d9b6028efb51cfff2a6850b0ced502/matrix_sdk/src/room/joined.rs#L402-L405 would have to get executed to ensure that members are present. Due to missing state it might also cause invalid Room Names which might be a guarantee thats going to be missing and I think the types should reflect that these kind of guarantees are missing when only having a room with a RoomID which is why I think "Joined" would not be the correct type to return at that time.

**Additional Context**
For understanding where I come from: This sdk seems to aim for being highlevel and these kind of details for me personally are those making the difference between being a highlevel sdk vs being a lowlevel sdk :) So thats why I consider this as a missing thing in the current sdk.

**Comment by johannescpk** [comment]
From the discussion with @MTRNord I feel like it makes sense to reflect some successful API calls (HTTP 200) somehow in the SDK, as depending on the endpoint it is a clear indication from synapse that something reliably changed, in case of joins that being an user now being part of `room_id`. Just not persisting and working with that info at all feels like losing information.

Also given the fact that the SDK in general doesn't believe to be part of a room despite synapse responding with 200 feels wrong. I can however see that it only makes sense for the SDK to populate certain information or fire certain events only upon actually receiving events. So it's probably a question of balance. I'm not too deep into the state store structure, but the proposal to have a separate type for not fully populated things (like e.g. a ~"`StrippedJoinedRoom`") sounds sane to me.

**Comment by poljar** [comment]
While I'm sympathetic to the fact that people would like to have an API that has a direct cause and effect relationship, e.g. `client.join()` to return the room, fundamentally this isn't how Matrix works, all the necessary changes for the room to be usable, at least in any capacity, are received through the sync.

You already mentioned which scenarios fail, though the biggest reason why this becomes a bad idea is E2EE support. E2EE support relies on room state to know some important things about the room:

1. That the room is encrypted via the `m.room.encryption` state event
2. The history visibility of the room via the `m.room.history_visibility` event
3. The list of members so it can start tracking E2EE devices of all the members in the room.

One simple use case would fail catastrophically unless additional logic isn't added to fetch the relevant state for the E2EE to work: 
- A bot joins the room and posts immediately a welcome message.

To mitigate this we would need to either add additional logic that fetches the relevant state events before sending an encrypted message, now this is already done so for the third case but I would advise against making this even more complex.

> For example at this time to ensure that get_joined_room returns a room of type Joined the user has to either wait for sync completion via a sleep

I think the problem here is that there isn't an easy way to wait for a sync to be done after you trigger a certain action, additionally you can't be certain that the room will be `Joined` even if you wait for the sync to happen, you could get booted out of the room by the time you sync.

> I only need the room id from it at that point in time.

You get that in the `join()` response, no?

I'm not really sure what you are doing that you claim to need only the room id, which you get in the response, but still want a struct that represents a room only containing a room id but I think waiting for a sync to be completed seems to be the better idea.

Instead, what do you think about having the sync loop emit heartbeat events using the [event_listener](https://docs.rs/event-listener/2.5.1/event_listener/) crate. That would allow users to wait for the current sync to complete, which would ensure that the room is there.

Furthermore, if people think that it's a good idea, that synchronization primitive could then be used to offer a higher level API where a `client.join()` call does the following:

1. Do the network request to join a room
2. Get the response and remember the `room_id` from the response
3. Wait for the sync heartbeat
4. Get the room out of the store and return it

This does mean that such a method would rely on having a running sync loop, but I think that documenting this fact and possibly offering a dumb version of the method would be enough to avoid any downsides of this.

**Comment by johannescpk** [comment]
> I'm not really sure what you are doing that you claim to need only the room id, which you get in the response, but still want a struct that represents a room only containing a room id

I think the idea was that the stripped down version of a room struct could still have all methods that only rely on the `room_id` to interact with the homeserver, e.g. `room.kick()`.

> Instead, what do you think about having the sync loop emit heartbeat events using the event_listener crate. That would allow users to wait for the current sync to complete, which would ensure that the room is there.

If I'm not mistaken that could also work with channels, e.g. `tokio::sync::broadcast` or similar. The issue here would be about timeouts, where if there's an issue with the sync you might run into something hanging forever, or if you specify a timeout the sync might succeed right after the timeout is hit. So it's not ideal, but could serve as workaround.

> E2EE support relies on room state to know some important things about the room

That's a very good point, so actually one should only start using a room if the encryption state is known, which makes sense. Does the SDK currently give guarantees about this? Like if you can acquire a `Room` it will have the encryption state or prevent doing things if it isn't known yet?

**Comment by poljar** [comment]
> I think the idea was that the stripped down version of a room struct could still have all methods that only rely on the `room_id` to interact with the homeserver, e.g. `room.kick_user()`.

How would you kick someone if you don't know if they are in the room? I guess you could fire out shotgun-like kicks/bans if you're a moderation bot but even then you would likely want to know the power levels of the room. Seems to be a fringe use-case event for the moderation bot.

> If I'm not mistaken that could also work with channels, e.g. `tokio::sync::broadcast` or similar. The issue here would be about timeouts, where if there's an issue with the sync you might run into something hanging forever, or if you specify a timeout the sync might succeed right after the timeout is hit. So it's not ideal, but could serve as workaround.

Tokio's broadcast isn't ideal for this use-case, considering that we don't want to block on the channel if it gets full, we instead want to discard messages. You can discard messages using Tokio's broadcast channels, but it's a bit more complicated than what we need, receivers get notified that they missed messages. Do note that [async_broadcast](https://docs.rs/async-broadcast/0.3.2/async_broadcast/) is built on top of [event_listener](https://docs.rs/event-listener/2.5.1/event_listener/).

It is a bit problematic every time you have two requests that can fail independently, though I think this is a far simpler solution than the proposed fake room struct.

> That's a very good point, so actually one should only start using a room if the encryption state is known, which makes sense. Does the SDK currently give guarantees about this? Like if you can acquire a `Room` it will have the encryption state or prevent doing things if it isn't known yet?

If you get a room out of the `Client` it is guaranteed to have all the state except the members. The method to get the members of the room ensures that they will be fetched from the server if they aren't already synced. There is an equivalent method to get the members that doesn't fetch the members from the server, but it is documented so and they link to each other (i.e. you might want to handle members manually for performance reasons, or because you can't make requests on you main thread). Lastly, before we send a message to an encrypted room, we fetch the members if they aren't synced.
