### ISSUE TITLE
Support OIDC discovery over the CS API

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#2910]
OIDC discovery through the .well-known is going to be replaced with a dedicated [CS API](https://github.com/matrix-org/matrix-spec-proposals/pull/2965/commits/e9e3ee19be70327fde44154b021b667a5250b622) to allow for OIDC authentication without requiring homeserver discovery to take place first. I would imagine this should be tackled in 3 parts (but I'm not 100% sure if this lines up with normal expectations:

- [ ] Adding [`/auth_issuer`](https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oidc-discovery/proposals/2965-oidc-discovery.md#get-auth_issuer) to Ruma and exposing the API from the SDK.
- [ ] Updating the authentication service to prefer this API over the old .well-known discovery mechanism.
- [ ] Once we're happy sufficient time has past for existing deployments to have updated, remove support for the old mechanism - _update: seems like plenty of time has passed for this now_

**Comment by sandhose** [comment]
I did update MSC2965 again to move the account management URL in the OP metadata, because I think it makes more sense: https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oidc-discovery/proposals/2965-oidc-discovery.md#account-management-deep-linking

Implementation in Synapse should come soon enough, and will keep the .well-known/matrix/client discovery for a while to avoid breaking clients
