### ISSUE TITLE
Look into replacing `sled`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-sdk#294]
[`heed`](https://docs.rs/heed/0.11.0/heed/index.html) is a high-level wrapper around LMDB, i think it'd be interesting to figure out if it has better performance, compatibility, and caching possibilities compared to `sled` (at the moment), and/or to allow these database backends to be swapped interchangeably.

**Comment by quininer** [comment]
I would want a sqlite backend, and it would be better if we could have a general abstraction that would allow us to use any custom storage engine.

**Comment by poljar** [comment]
Such an abstraction exists: https://github.com/matrix-org/matrix-rust-sdk/blob/3d734a120d8e934b7c8e299e0bfc9509632b2fb1/matrix_sdk_base/src/store/mod.rs#L91. You can implement a custom store and use it.

As for now, there aren't any show stoppers that would make me move away from sled and I don't have the bandwidth to support multiple store implementations.

**Comment by jplatte** [comment]
Other options mention on Matrix today:

* [BonsaiDb](https://bonsaidb.io/)
* [Persy](https://persy.rs/)

Both written in Rust, so presumably don't need a C toolchain which could give us easy cross compilation once olm is also replaced by vodozemac (which should be pretty soon!).

**Comment by poljar** [comment]
Another one:
* [Sanakirja](https://docs.rs/sanakirja/latest/sanakirja/)

Which has multi-process support, which might be relevant for the iOS use-case where currently two sync loops are going on. One for the notifications and one for the main process.

**Comment by gnunicorn** [comment]
note about BonsaiDB, [from their docs](https://dev.bonsaidb.io/release/guide/integration/overview.html):
> However, the underlying storage layer that BonsaiDb is built upon, [sled](http://sled.rs/), does not support multiple processes writing its data simultaneously.

**Comment by gnunicorn** [comment]
maybe https://github.com/symmetree-labs/infinitree ?

**Comment by gnunicorn** [comment]
don't forget about https://github.com/paritytech/parity-db

**Comment by bnjbvr** [comment]
A new contender recently appeared: https://github.com/cberner/redb/

Pure Rust, claims almost as fast as LMDB in the README.md.

**Comment by jplatte** [comment]
Unfortunately it is mmap-based, so fundamentally incompatible with accessing the DB from multiple processes at the same time, which seems like is going to be a hard requirement for whatever we replace sled with.

**Comment by P-E-Meunier** [comment]
I'm the author of Sanakirja and reached this thread while reading about news in Matrix. If you need any help let me know.

**Comment by jplatte** [comment]
@P-E-Meunier Thanks for the offer! I have started work on a crypto-store based on Sanakirja, but it's not clear to me how I would use arbitrarily-sized (byte)strings in there, both for keys and values. I got the basic setup working and thought `[u8]` key / value would work, but then hit the 510 byte limit in `impl UnsizedStorable for [u8]`. I started looking into how Pijul uses sanakirja, but didn't get very far yet. The current state of my work can be found [here](https://github.com/matrix-org/matrix-rust-sdk/commit/b2b97f6f62caa092464894e85eb8dc66baf81719).

**Comment by P-E-Meunier** [comment]
This isn't a hard limit, Sanakirja is a framework rather than a database, its main duty is to manage memory (including optional reference counting if you need to fork your datastructures) in an mmapped file, in a fully transactional way.

You can write many different datastructures on top of that, B trees are just one particular datastructure, but I've worked on others (ropes, for example). It mostly depends on what operations you want, but one workaround for the 510b limit is to create a new type of pages for storing large chunks of contiguous data, and reference these pages in the tree. The only tricky part is that the allocator now needs to return contiguous pages, but that isn't hard.

If you don't need your values to be contiguous in memory (or can afford to copy them rather than work with pointers), things will be easier. One significant advantage you'll gain if you can use the current allocator is that one can implement it on top of more exotic backends: Pijul uses the same code when working on-disk and in zstd-compressed files. You could also potentially use other databases (such as replication/HA tools).

Just tell me what you need, I may be able to implement it if it isn't too complicated.

>  I started looking into how Pijul uses sanakirja, but didn't get very far yet.

This is at the same time a good and a terrible idea: a good one since it is possibly the most "real-world" use of Sanakirja currently deployed, and a terrible one because at the time of starting Pijul, GATs hadn't even started in unstable Rust. Therefore, I decided to do the compiler's job of monomorphising manually, using macros. But then that gave me too much freedom to express type constraints that made "repos-in-zstd" possible, and these constraints can't be expressed in Rust's type system without the manual monomorphisation.

So, Pijul's way is also possibly the most convoluted way to use Sanakirja.

**Comment by P-E-Meunier** [comment]
Looking at your code, Pijul can handle concurrent readers and writers, you don't need to drop your reader before starting a writer. The exact constraint is much more flexible than this, but a first approximation is that you need to drop the readers before committing a writer.

**Comment by jplatte** [comment]
But it reduces contention to drop the reader earlier, no? Anyways, the biggest concern for us right now is to get something that works. I'm not at all experienced with low-level details of databases, nor do I want to optimize things a lot right now (except we need to be able to open the DB without immediately running out of the memory restrictions for background processes on iOS). We have sled as an existing backend which runs into those limits, which is one reason we are now spending more time on trying out replacements.

> If you don't need your values to be contiguous in memory (or can afford to copy them rather than work with pointers), things will be easier.

I think we can totally afford to copy rather than working with pointers. I guess the alternative would be an `io::Read` implementing type, but due to https://github.com/serde-rs/json/issues/160, that will be much slower, and I assume it won't be easier to implement either, right?

**Comment by P-E-Meunier** [comment]
Well, let me try something first ;-) I believe this can be solved during the end of my lunch break.

**Comment by P-E-Meunier** [comment]
Ok, I just published the allocator (Sanakirja 1.3), although I don't think it will be very useful for now, it seems I'll have to think a bit more about the best way to use it, I tried various things without success.

The main issue is that if you're storing bytestrings of widely different sizes, you could end up wasting disk space, so I tried to mitigate against that, but didn't find a convincing way. I'll come back to it in the next few days.

**Comment by jplatte** [comment]
Sorry, I don't understand – what changed exactly?

**Comment by P-E-Meunier** [comment]
The `AllocPage` trait has a new method, `alloc_contiguous`, which `MutTxn` implements. I tested it on small examples, it seems to work ok. Now the only thing missing is the type of large values using that allocator.

**Comment by P-E-Meunier** [comment]
No, but I looked at it again last night and I believe I found a way. I'll keep you posted.

**Comment by P-E-Meunier** [comment]
Alright, using Sanakirja 1.3.1 you can the following:
`````rust
use sanakirja::*;

fn main() {
    let env = Env::new_anon(409600000, 1).unwrap();
    let mut txn = Env::mut_txn_begin(&env).unwrap();

    let mut db: btree::UDb<u64, Slice> = btree::create_db_(&mut txn).unwrap();
    btree::put(&mut txn, &mut db, &0, &(&b"blabal bilbli"[..]).into()).unwrap();

    let v = vec![b'a'; 5000];
    btree::put(&mut txn, &mut db, &1, &(&v[..]).into()).unwrap();

    txn.set_root(0, db.db);
    txn.commit().unwrap();

    let mut txn = Env::mut_txn_begin(&env).unwrap();
    let mut db: btree::UDb<u64, Slice> = btree::UDb::from_page(txn.root(0).unwrap());
    println!("{:?}", btree::get(&txn, &mut db, &0, None).unwrap().unwrap().1.as_bytes(&txn));
    let bb = btree::get(&txn, &mut db, &1, None).unwrap().unwrap().1.as_bytes(&txn).unwrap();
    println!("{:?} {:?}", bb.len(), bb.iter().all(|c| *c == b'a'));

    txn.set_root(0, db.db);
    txn.commit().unwrap();
}

`````````

Some words of caution:

- Sanakirja is relatively low-level, as you can see. The main advantage is that you can store complex Rust types as raw bytes, and write well-typed wrappers that don't copy any bytes.
- In particular, you should have at least some understanding of what the pointers are. A `Db`, for example, is a pointer to an allocated page. If you don't retain it, you'll leak memory. If you store it twice (without forking it), you'll have a use-after-free.
- The roots may store any kind of value, but usually
- About storing this new `Slice` type, it points to another page if the value is large enough, and stores it on the page otherwise. In principle, `btree::del` takes care of deallocating the values.

If you're unsure, you can ask me. The Rust typesystem isn't sufficiently expressive to provide a safe interface to Sanakirja, which means that the rules aren't that simple.

**Comment by jplatte** [comment]
> * In particular, you should have at least some understanding of what the pointers are. A `Db`, for example, is a pointer to an allocated page. If you don't retain it, you'll leak memory. If you store it twice (without forking it), you'll have a use-after-free.

So you mean in the example above,

- If the call `txn.set_root(0, db.db);` is removed, memory is leaked
- If the call is kept but I also add `txn.set_root(1, db.db);` afterwards, that is UB

?

**Comment by P-E-Meunier** [comment]
Yes. About `set_root`, note that Sanakirja allocates memory atomically: all the allocations from a `MutTxn` are done atomically at commit time.

So, while using a `Db` from one `MutTxn` in another transaction might "work", I still recommend that you store it in the transaction (possibly in a root), and read it back in the other transaction, to benefit from these guarantees.

For example, if you follow this advice, and some failure happens after commit (my usual hypothesis is power failure), no memory will be leaked and no reference will be left hanging.

**Comment by jplatte** [comment]
In that case I don't have the confidence needed to continue with the sanakirja crypto store prototype. Long-term, we might be interested in building a higher-level safe API on top of a version of sanakirja with anything that can cause UB marked `unsafe` + documented safety preconditions, but right now we're probably going to try getting sqlite to work.

**Comment by P-E-Meunier** [comment]
No problem. If you know what you want, I can give you a safe wrapper. How many tables? Do you need nested datastructures (a Db where the keys and/or values are also Db)?

**Comment by gnunicorn** [comment]
came accross [surrealdb](https://docs.rs/surrealdb/1.0.0-beta.8/surrealdb/) this morning...

**Comment by jplatte** [comment]
The default store backend is sqlite now, and we will likely kill sled entirely soon enough.

**Comment by Hywan** [comment]
And sled has been killed, RIP. I'm closing this issue :-).

**Comment by tshepang** [comment]
hm, there was a(n alpha) release just last week

**Comment by poljar** [comment]
Indeed there [was](https://crates.io/crates/sled/1.0.0-alpha.118). Though what @Hywan meant is that the `sled` based store implementation has been removed from the repo.

Nowadays we're having slightly different requirements so bringing the `sled` store back is very unlikely.
