### ISSUE TITLE
Key migration From To issue

### ISSUE THREAD

**Issue by toger5** [matrix-org/matrix-rust-sdk#3010]
While reloading EW the console logged key migrations.

It migrated more keys than what it claimed to be availabel:
```
DEBUG matrix_sdk_indexeddb::crypto_store::migrations: Migrating session 111700 of 104818
    at /home/runner/.cargo/git/checkouts/matrix-rust-sdk-1f4927f82a3d27bb/3e17fc2/crates/matrix-sdk-indexeddb/src/crypto_store/migrations.rs:351
```

I have no idea if this is a sirious issue but `111700 of 104818` definitly looks broken (even if its just the logging)

**Comment by andybalaam** [comment]
Thanks @toger5 - we are fairly sure this is because the migration modifies the table as it's walking through it, meaning that it sometimes re-encounters the same item twice (because the actual migration is a change to the key, so items get re-added later in the table). When it re-encounters an item it won't take any action, so nothing bad will happen because of this (except it takes longer than it otherwise might).

Given that the vast majority of users won't encounter this because they will never have a non-empty pre-version 8 DB, and it's largely a cosmetic issue, I will close this issue.

Thanks for reporting it - I agree it is a worrying message, but we think it's mostly harmless in this case.
