### ISSUE TITLE
Custom `Context` for event handler

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#323]
Two possible implementations

```rust
client.register_event_handler(
    move |ev: TheEventType, my_ctx: Thing, client: Client| {
        // do stuff
    }
).await

impl_event_handler_context!(Thing);
```

and

```rust
use matrix_sdk::event_handler::Context;
client.register_event_handler(
    move |ev: TheEventType, my_ctx: Ctx<Thing>, client: Client| {
        // do stuff
    }
).await;
```

The former is what we probably want to have a go at first since it gives full type safety.

Matrix chat context: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$NMoyTo9pfLvYO6pJMREpPVC5nJYFigR_EIkC2q6fxTM?via=matrix.org&via=kde.org&via=gnome.org

Follow-up from https://github.com/matrix-org/matrix-rust-sdk/issues/321

**Comment by jplatte** [comment]
Actually, the former would have to be based on the latter (except the `Ctx` type could be `doc(hidden)`) so when it comes to implementation it's all the same thing 🙂

**Comment by jplatte** [comment]
Since you said on Matrix that you're interested in tackling this, here is what has to be done:

* Add a dependency to [anymap](https://crates.io/crates/anymap)
* Add `anymap::Map<dyn CloneAny + Send>` (bounds are an example, idk what's actually needed) field to the `Client`
* Add `register_event_handler_context` method that inserts sth. into the anymap
* Add at least one of
  * A type that's roughly `pub struct Ctx<T>(pub T);` (I recommend making the field public and nameless but other approaches could work too) which implements `EventHandlerContext` by looking up the type via `data.client`
  * A small macro¹ that implements `EventHandlerContext`, either through a public anymap lookup method on the client or if the `Ctx` type exists through that

¹ probably easier to do macro_rules for now since there's no proc-macro crate in the SDK yet

**Comment by jplatte** [comment]
Actually, after thinking it through I'm less and less convinced by the macro solution. It would only work for your own trivially-copyable types, i.e. instead of `Arc<Thing>` you would need `struct Thing(Arc<InnerThing>);` unless you would trade away the "full type safety" and implement `EventHandlerContext for Arc<T> where T: EventHandlerContext`, at which point the derived trait offers only a slight simplification of a subset of event handler signatures.

**Comment by johannescpk** [comment]
I'd say being able to define a specific type and with that achieve "full type safety" is desirable. What issue do you see with the requirement of the type being cloneable?

**Comment by jplatte** [comment]
The issue I see it that it has to be a type defined by yourself. It couldn't be a `sqlx::SqlitePool`, or `Arc<MyAppData>` or something like that, because you can't implement types you didn't define yourself for types you didn't define yourself.

**Comment by johannescpk** [comment]
For my use case I mostly have a crate-local wrapper types anyway - and having that additional type safety would be nice to have. But right, for external types it does need the `Context<T>` then.

**Comment by johannescpk** [comment]
I wonder tho, it's not guaranteed that the consumer actually registers `Thing`, in which case it would again fail at runtime. So actually not much of a difference, you have to take care that you correctly sync registering and specifying the callback argument. Which I guess makes the macro kinda redundant.

**Comment by jplatte** [comment]
I'll implement this.
