### ISSUE TITLE
sqlite: deadpool sync can cause panics

### ISSUE THREAD

**Issue by maan2003** [matrix-org/matrix-rust-sdk#3467]
https://github.com/bikeshedder/deadpool/issues/325

just want to track the deadpool sync can cause panic, just hit this with matrix sdk. 

for searchablity: 
panicked at
deadpool-sync-0.1.2/src/lib.rs:122:43: called `Option::unwrap()` on a `None` Value

**Comment by Hywan** [comment]
Thanks. We are waiting a new release of `deadpool` to close this issue then.

**Comment by bikeshedder** [comment]
I'm curious how you managed to actually trigger this issue. I can only think of one way how this error could be triggered and it either needs the pool to be resized or closed:

- https://github.com/bikeshedder/deadpool/issues/325#issuecomment-2148401515

Was this error only ever observed on shutdown? That would make an awful lot of sense if the sync task was still running but the tokio executor gone, all futures dropped and the pool itself gone as well.

Otherwise I don't see how this error could ever be triggered. :thinking:

**Comment by maan2003** [comment]
it just happens in production It is rare, but has happened multiple times in our matrix client. I don't have good backtrace / logs for this.

But i can confirm that It was not executor shutdown.

**Comment by bikeshedder** [comment]
I just release deadpool-sync 0.1.4 including this patch:

- :adhesive_bandage:  https://github.com/bikeshedder/deadpool/commit/2216358534b1d210ad81d6fc21f2357bdbe21b60
- :package: https://crates.io/crates/deadpool-sync/0.1.4

As it is a non-breaking change it should be just a matter of running `cargo update`  for everyone.

I'm still a bit worried as I can't imagine how you managed to trigger this bug in the first place.

I mean... it was a bug for this very rare case of a shutdown/resize of a very active pool and it should now be fixed... but as you confirmed that it didn't happen during shutdown I'm very worried that there is a bigger dragon lurking somewhere else. :dragon:

**Comment by maan2003** [comment]
I will let you know when something else breaks :)
