### ISSUE TITLE
send queue: dependent actions system

### ISSUE THREAD

**Issue by frebib** [matrix-org/matrix-rust-sdk#3663]
Under less-than-optimal network situations, EX fails to send reactions and "eats" them. It'd be cool if the send queue (+retry mechanisms) was used for reaction sending. Benji suggests that it would probably improve in less duplicate code https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$hGjNwhDvoNeK15O6h3DhmO7wlVrzNsdDBBssJ9o4iYQ?via=matrix.org&via=element.io&via=envs.net

**Comment by bnjbvr** [comment]
Ok, so I'm stealing this issue because I've found about one extra use case that is quite similar and would be handy.

Right now, there's a possible race condition in the timeline: if you try to edit/abort an event that's being sent, then the send queue refuses to edit/abort it (because it's being sent), and the timeline will assume it's *been* sent, so will look for a corresponding event that has a matching transaction id. In that case, it results into a no-op, because there's no remote echo for that event yet.

Since applying a reaction requires the event to be sent, an extension of that is to consider edits/aborts as pending operations too, and have the send queue remember them. So the send queue would now allow edit/abort items that are *being* sent, and would apply pending operations later:

- if the event could be successfully sent, then send a redaction/edit event later
- otherwise, apply the redaction/edit on the local echo itself

This would work also for reactions, which would only take the success branch and send an event after the event's been sent.

Now, when editing something in the timeline:
- either it's a local echo at the time the edit operation is done;
  - if the send queue still knows about the local echo (it was being sent, or not): then the send queue either uses a local echo edit, or a pending operation if it's being sent
- or the local echo isn't known by the timeline anymore: the timeline tries to find a matching remote event_id for that transaction id

I think that will cover all the cases, and avoid all race conditions.

As a result, there's a bit of code duplication that needs to be handled: editing/aborting could happen either at the timeline level (second top-level bullet in the above list), or at the send queue level (first top-level bullet).

Some high-level items needed for this work:

- [ ] migration for a new table for the pending operations in the state storage
- [ ] new APIs to insert/edit/remove in that pending operations table
- [ ] adapt the send queue to make use of this
- [ ] extract the edit code from the timeline and put it in the SDK, so it can be reused everywhere
- [ ] (performance bonus) have the event cache provide an API to retrieve a known event by ID, to avoid events network lookups in the above `edit()` code

**Comment by frebib** [comment]
🎉  Thanks 😍
