### ISSUE TITLE
Add members to `MessageLikeEventContent.RoomRedaction`

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#3859]
In the context of https://github.com/element-hq/element-x-android/issues/3310, the application needs to know which Event have been redacted to be able to cleanup any displayed notification.

Adding the `roomId` and the `eventId` as fields of `MessageLikeEventContent.RoomRedaction` should be enough for the application to be able to remove the notification for the redacted event.

Happy to test a work in progress branch using EXA.

**Comment by jmartinesp** [comment]
Just to confirm, how do you plan to listen for these events, by receiving a notification of a redaction?

Could you test https://github.com/matrix-org/matrix-rust-sdk/compare/misc/add-info-to-ffi-room-redaction-event and let me know if it's what you needed? I didn't add the `roomId` since you should already be able to get it from the surroundings of calling code (either you have a reference to the room that returned this event, or you have the room id in the notification data if I'm not mistaken).

**Comment by bmarty** [comment]
> Just to confirm, how do you plan to listen for these events, by receiving a notification of a redaction?

Yes, a Push :)

**Comment by bmarty** [comment]
It's working fine, thanks!
