### ISSUE TITLE
send_queue: persist send errors

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#3973]
When a message fails to send with one of the `EventSendState` cases below, the next time the timeline is opened it send state has become `SendingFailed`:

- `VerifiedUserHasUnsignedDevice`
- `VerifiedUserChangedIdentity`
- `CrossSigningNotSetup`
- `SendingFromUnverifiedDevice`

These cases don't exist in the UI crate as they're mapped [directly in the FFI](https://github.com/matrix-org/matrix-rust-sdk/blob/1dd8c908c590ac1dc78815869d18ea79c3cd14ba/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L983-L1004), and so they aren't being persisted to the store.

In practice this looks like so Element X, meaning the user can't resolve the send failure once they've closed the room:

https://github.com/user-attachments/assets/c4a9c4fa-efeb-403b-863c-2626410730cc

**Comment by bnjbvr** [comment]
Those errors would need to be saved in the send queue on-disk backend:

- change `QueuedEvent` in the base state store trait so it contains the error: let's replace `is_wedged: bool` by an `error: Option<YourErrorEnumHere>`, so `is_wedged` become equivalent to `error.is_some()`
- update databases/backends so they include this error, with a minimal migration: is_wedged = true => the error is set to Some(dummy)
- in [`QueueStorage::mark_as_wedged`](https://github.com/matrix-org/matrix-rust-sdk/blob/ef6237045e999f15a6cf652296e69c0ac6bc33d3/crates/matrix-sdk/src/send_queue.rs#L681), include the observed error when saving it
- change a `LocalEchoContent::Event` so it includes the optional error instead of [`is_wedged`](https://github.com/matrix-org/matrix-rust-sdk/blob/ef6237045e999f15a6cf652296e69c0ac6bc33d3/crates/matrix-sdk/src/send_queue.rs#L1137)
- use this error when handling a local echo in the timeline, [instead of using a dummy error](https://github.com/matrix-org/matrix-rust-sdk/blob/ef6237045e999f15a6cf652296e69c0ac6bc33d3/crates/matrix-sdk-ui/src/timeline/controller/mod.rs#L1224-L1237)
- also, don't forget to test this :clown_face: 

Wanted to say good luck, we're all counting on you.
