### ISSUE TITLE
Add support in timeline for the new MegolmError `SenderIdentityNotTrusted` when cross-signed `TrustRequirement` is enabled

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#4048]
Part of https://github.com/element-hq/crypto-internal/issues/308.

Modify TimelineEvent to expose New Megolm errors when TrustRequirement is CrossSigning*, add new cases to UtdCause.

See https://github.com/element-hq/crypto-internal/issues/353 for the new error to show in timeline

**Comment by richvdh** [comment]
Having discussed this a bit with the rust team, the concern was raised that the types proposed allow for a conflict in state between `encryption_state` and `event`.  (For example: what would it mean if `encryption_state` indicated a UTD, but `event` was a successful decryption?)

Instead: it was proposed to replace `event` and `encryption_info` in `TimelineEvent` and `SyncTimelineEvent` with a new enum:

```rust
enum TimelineFoo {
    Utd {
        event: Raw<EncryptedEvent>,
        cause: UtdCause,
    },
    PlainText {
        event: Raw<T>,
    }
    Decrypted {
        event: Raw<T>,
        info: EncryptionInfo,
    }
}
```

(better name needed, obvs)

We should also update `OlmMachine::decrypt_room_event` to return a `TimelineEvent` with `TimelineFoo::Utd` instead of an `Err`, on UTD errors.

**Comment by richvdh** [comment]
@BillCarsonFr the rust bits of this are now done - can you take this over to add the UI layers?

**Comment by BillCarsonFr** [comment]
> [@BillCarsonFr](https://github.com/BillCarsonFr) the rust bits of this are now done - can you take this over to add the UI layers?

Working on it, I think this issue can be closed. The remaining work is tracked in other issues

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/4070
