### ISSUE TITLE
 Ignore only m.direct room entry to non-existing room instead of ignoring all.

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#4125]
Initially created at https://github.com/element-hq/element-x-android/issues/3659, but I believe that the fix has to be done here (or in Ruma?)

**Comment by jmartinesp** [comment]
Are we sure this isn't a problem with the direct room data being malformed somehow? We've had some history of whole JSON lists/objects being discarded because serde couldn't deserialize part of them, and AFAICT [the code that processes direct rooms](https://github.com/matrix-org/matrix-rust-sdk/blob/3ce2f16d556ec519116a86fe746967d8627985f1/crates/matrix-sdk-base/src/response_processors.rs#L88) will just add the flag to rooms matching some ids, remove it from the rest and [skip any room that it can't find](https://github.com/matrix-org/matrix-rust-sdk/blob/3ce2f16d556ec519116a86fe746967d8627985f1/crates/matrix-sdk-base/src/response_processors.rs#L88).

**Comment by bmarty** [comment]
@spaetz do you have more input to provide to help investigating this issue?

**Comment by spaetz** [comment]
Will do some tests and report back here. can take a few days though. What I can say is the the m.direct data validated fine using a json validator and nothing stood out. Will report after some tests.

**Comment by spaetz** [comment]
OK,  experimented with my m.direct data, and added non-existing rooms and/or user names. And even after deleting the cache, EXA worked fine, showing all persons in the persons tab. So, I have to conclude that my m.direct json was somehow corrupted in subtle ways and will close this issue. Will reopen a new one in the Rust SDK if I ever re-encounter this. Sorry for the noise.

P.S. please close this issue, I don't have the permission to do so :-)
