### ISSUE TITLE
A bug of filed `user_ids` of struct `Message`

### ISSUE THREAD

**Issue by Demolemon11** [matrix-org/matrix-rust-sdk#4221]
My `UserId` is `@demolemon:matrix.org`.
One of my friend's `UserId` is `@tyreseluo:matrix.org`.
A person's `UserId` is `@empire:mannheim.ccc.de`.
Another person's `UserId` is `@Bronson:matrix.org`.

**According to my initial observation, only those with the same suffix can be collected into `user_ids`'s `BTreeMap`.**

![Screenshot from 2024-11-06 13-25-58](https://github.com/user-attachments/assets/ff751fd9-e37b-429f-a497-b079c28247f4)

![Screenshot from 2024-11-06 13-25-22](https://github.com/user-attachments/assets/01be7164-4017-496a-9b8b-9fdceac619f3)

![Screenshot from 2024-11-06 13-25-39](https://github.com/user-attachments/assets/2eb5eb3d-b5e6-4ff1-86b7-3de73334426d)

**Comment by bnjbvr** [comment]
If you want to make useful issue reports, please provide useful information, not screenshots:

- what code you're using to trigger the issue,
- what you're expecting to see,
- what you're observing in practice

Any issue without any of these three pieces of information makes it super hard for us to be helpful in any ways. Also, I wonder if your issue should've been filed on the Fractal repo (maybe that's why you closed it).
