### ISSUE TITLE
Should assert_identity really be part of RequestConfig instead of ClientConfig?

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#524]
@johannescpk you added this. The code currently only ever checks whether it's set on the client `RequestConfig` instance, rather than the one that can be passed for individual requests, making setting it anywhere else a no-op. Do you know how this came to be?

**Comment by johannescpk** [comment]
The idea was to be able to configure it per request. But you're right, somehow a bug sneaked in there - seems no test is covering per request configuration.

https://github.com/matrix-org/matrix-rust-sdk/blob/36e4836c06e592db7281834a8514461a26c309ed/crates/matrix-sdk/src/http_client.rs#L131

Should really be `!config.assert_identity`.

**Comment by jplatte** [comment]
> The idea was to be able to configure it per request.

Why though? The appservice crate has one matrix client per identity, why would it ever not include that identity in a request?

**Comment by johannescpk** [comment]
That's why you can configure it globally as well. Solely from C2S spec perspective, you can decide for every request independently whether you want to assert the identity or not - so it felt like the correct thing to do. But if you feel like it's feature creep I'm fine with only supporting one global configuration, be it client or request configuration - since clearly no one was using per request configuration up until now anyway.
