### ISSUE TITLE
Implement MSC3061: Sharing room keys for past messages 

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#580]
From element-ios created by [manuroe](https://github.com/manuroe): vector-im/element-ios#4947  

As per [MSC3061](https://github.com/matrix-org/matrix-doc/pull/3061)

See https://github.com/vector-im/element-android/issues/4153

**Comment by jplatte** [comment]
I've created a Ruma issue for this as well: https://github.com/ruma/ruma/issues/1104

**Comment by poljar** [comment]
I'm aware of the flaws of the current approach, that is one of the reasons why this isn't yet implemented in the rust-sdk. A proper solution would need more time.

Thanks for reminding me.

**Comment by richvdh** [comment]
@poljar if there are other flaws it might be good to link them here, so we can make sure that they are correctly addressed in whatever solution we use for the rust-sdk?

**Comment by poljar** [comment]
The main problems are:
1. The authenticity of such keys can't be proven
2. There's no way send over a batch of room keys, so `m.forwarded_room_key` is used
3. Because of no 1 it's important to treat such keys in a special way, but no 2. makes it hard to do so.

What I proposed was to have a separate event type, which will separate the concepts and allow a batch of room keys to be sent over.

**Comment by dkasak** [comment]
Given the [reversion of MSC3061](https://github.com/matrix-org/matrix-spec-proposals/pull/3061#issuecomment-2444845098) following the [vulnerability disclosure](https://matrix.org/blog/2024/10/security-disclosure-matrix-js-sdk-and-matrix-react-sdk/), closing this as not planned.
