### ISSUE TITLE
Add tests for notification handling

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#663]
In encrypted rooms, we can't rely on notifications from the server. We should test the code paths that generate notifications locally based on timeline events.

**Comment by Hywan** [comment]
cc @bnjbvr Did you add tests for that?

**Comment by bnjbvr** [comment]
Since the original issue is a bit unclear, I'll assume this was about receiving notifications in general. Nowadays we do have the `NotificationClient`, specialized for resolving a notification based on a room and event IDs, and this will nicely handle encrypted rooms. This is quite tested too. So not sure there's much to add here; if I've missed something, let's open a new issue!
