### ISSUE TITLE
Json Store in Windows "looses"/"forgets" json ending on files and doesn't write state resulting in crash on restart

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-rust-sdk#71]
Apparently on my PC or Windows in general when using the json store the files created for rooms a) don't seem to end on "json" and b) are not being written to (probably because of a).

**Comment by poljar** [comment]
I believe the issue is that the room id contains a `:` which according to [this](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) is a reserved character on NTFS.

The quick fix would probably be to HTML escape the file names, long term we'll want to use a smarter database for the store, either sled or reuse SQLite as a key/value store.

**Comment by MTRNord** [comment]
I am now also trying to make a sled store :) Lets see if that works
