### ISSUE TITLE
Verify device for debugging

### ISSUE THREAD

**Issue by bitfriend** [matrix-org/matrix-rust-sdk#775]
I am making library based on `matrix-rust-sdk`.
I tried to get `room` from `client` on windows, but it failed.
```rust
    use anyhow::Result;
    use zenv::{zenv, Zenv};

    use crate::api::{login_new_client, room::Room, Client};

    #[tokio::test]
    async fn test_invited_from() {
        let z = Zenv::new(".env", false).parse().unwrap();
        let base_path: &str = z.get("BASE_PATH").unwrap();
        let username: &str = z.get("USERNAME").unwrap();
        let password: &str = z.get("PASSWORD").unwrap();

        let client: Client = login_new_client(
            base_path.to_owned(),
            username.to_owned(),
            password.to_owned(),
        )
        .await
        .unwrap();

        let room_id: String = "!jXsqlnitogAbTTSksT:effektio.org".to_owned();
        let room: Room = client.room(room_id).await.expect("Expected room to be available");
    }
```
I guess it is because my windows device is not verified.
How can I verify my windows device?
I installed `element desktop` on my windows.

**Comment by zecakeh** [comment]
Hi,

Whether your device is verified or not should only affect encrypted messages.

I don't know what exactly happens in `login_new_client`, but you need to trigger at least an initial sync before being able to see which rooms the user is in. See the [command bot example](https://github.com/matrix-org/matrix-rust-sdk/blob/matrix-sdk-0.5.0/crates/matrix-sdk/examples/command_bot.rs) that does that before handling commands.

Also, shouldn't `client.room()` be `client.get_room()`?

**Comment by bitfriend** [comment]
Yes, initial sync was problem.
I could solve problem using `sync_once`.
Thank you for your advice.

**Comment by bitfriend** [comment]
I made sample code using the [command bot example](https://github.com/matrix-org/matrix-rust-sdk/blob/matrix-sdk-0.5.0/crates/matrix-sdk/examples/command_bot.rs).
I called `timeline_backward` after `sync_once` but I couldn't get the past invitation event.
https://github.com/bitfriend/effektio/blob/59bf95e366203bd69d9363ac4ded56e7a15c479a/native/effektio/src/api/room.rs#L710
Can you please help me?

**Comment by zecakeh** [comment]
That would be because the timeline feature only works for joined rooms.

What we do in the client I'm working on is that we look at the sync response to get the corresponding state event. However, since the event should be available in the store it would probably be useful to add a method to `room::Joined` in the SDK to get the invite sender.

**Comment by bitfriend** [comment]
I don't know how `element app` fetches the past invitation event on launch.
Not found the example that uses `get_state_event(StateEventType::RoomMember, xxx)`.
Can you help me?

**Comment by bitfriend** [comment]
What is difference between `sync_once` and `sync`?
```
        let mut client_builder = MatrixClient::builder().homeserver_url(homeserver_url);

        #[cfg(feature = "sled")]
        {
            let state_store = matrix_sdk_sled::StateStore::open_with_path(base_path)?;
            client_builder = client_builder.state_store(state_store);
        }

        let client = client_builder.build().await.unwrap();
        client.login(&username, &password, None, Some("command bot")).await?;
        println!("logged in as {}", username);

        client.sync_once(SyncSettings::default()).await;

        let settings = SyncSettings::default().token(client.sync_token().await.unwrap());
        client.sync(settings).await;
        println!("456");
```
If I call `sync`, app halts on there and I can't get `456` log.
I guess `get_state_event` is getting `None` because store sync was not done properly.

**Comment by bitfriend** [comment]
This function is printing `None`.
```
    pub async fn invited_from(&self) -> Result<String> {
        let room = if let MatrixRoom::Invited(r) = &self.room {
            r.clone()
        } else {
            bail!("Can't get a room we are not invited")
        };
        RUNTIME
            .spawn(async move {
                let ev = room
                    .get_state_event(StateEventType::RoomMember, "")
                    .await?
                    .and_then(|e| e.deserialize().ok());
                println!("{:?}", ev);
                return Ok("123 - invited".to_owned());
            })
            .await?
    }
```
Can you please let me know why it fails?

**Comment by zecakeh** [comment]
> What is difference between `sync_once` and `sync`?

The [`sync`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.Client.html#method.sync) docs seem pretty clear to me about that. Is there something we could add that makes the different use cases clearer?

> Can you please let me know why it fails?

The reason it fails is that this method returns an `AnySyncStateEvent` while in invited rooms we only receive `AnyStrippedStateEvent`, so they are stored in a separate place and can't be accessed with this method.

Like I said previously, there's no method available to get this event from the store. You could look at the return value of `sync_once` and look for the event you're looking for inside. You could also use [`register_event_handler`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.Client.html#method.register_event_handler) like the [autojoin example](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/examples/autojoin.rs).

Note also that your call to `get_state_event` would also always return `None` because the `state_key` of a [`RoomMember`](https://spec.matrix.org/unstable/client-server-api/#mroommember) event is the user ID of the user it applies to, so requesting a room member state event with an empty state key will never return anything.

**Comment by zecakeh** [comment]
I'm realizing now that you're asking the same thing as in #752, so the rest of the discussion will take place there
