### ISSUE TITLE
`Client::send` fails with `assert_identity` enabled [regression]

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#821]
**Describe the bug**
Due to the refactoring in https://github.com/matrix-org/matrix-rust-sdk/commit/12d1607cdce6b63eb45195283d08160e40bc77a2 it is no longer possible to enable `assert_identity` and then `Client::send()` requests that don't pass a `session` to the underlying `HttpClient::send()`. In turn this means that `Client::send` generally no longer works anymore, as it is calling `Client::server_versions()` internally, which passes `None` as session.

**To Reproduce**
Instantiate `Client` with `assert_identity` enabled and try to `Client::send()` a request.

**Additional context**

Supersedes https://github.com/matrix-org/matrix-rust-sdk/issues/819

**Comment by jplatte** [comment]
I don't fully understand, why is it a problem that no identity assertion is sent for this endpoint? It doesn't require auth. 

I think the fix here is to copy the discovered server versions from the main appservice client to the others, rather than having each individual appservice client do a server versions check.

**Comment by jplatte** [comment]
I think my suggestion is actually going to fully fix this issue. By doing that, server_versions will no longer call request_server_versions for secondary appservice clients.

**Comment by johannescpk** [comment]
But the initial call would still need to work, which it currently does not. And by fixing it, it's fixed fully as well.
