### ISSUE TITLE
Expose storage interface for WASM bindings

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-rust-sdk#941]
We need a way to persist data for the OlmMachine to use in practice. Ideally, this is done in a way where we can dictate the storage structure and mechanism rather than have it dictated for us (largely so we can use secure storage techniques not immediately available to the Rust SDK). 

The other rationale is we already have a database of crypto data in web clients, so it'd be nice to re-use those databases instead of having to maintain concurrent stores and migrate between the two. 

A prototype interface for this might be:

```
class Storage {
  public abstract readIdentityKeys();
  public abstract readGroupSession(id);
  public abstract writeGroupSession(session);
  // etc
}
```

**Comment by Hywan** [comment]
Hello Travis,

Thanks for the proposal.

We've been thinking a lot about this proposal. My main concern here is performance. We will travel from JS to Rust to JS to Rust to JS (calling a Rust API from JS, then Rust will execute the storage in the JS land, then come back to Rust, to finally end the procedure in JS) multiple times, and crossing the Wasm boundary is not cheap (just like any ABI boundary). I've strong reasons to think it will hurt performances.

I think we should spend more times to discuss about the underneath problem you're trying to tackle here. Like:

> (largely so we can use secure storage techniques not immediately available to the Rust SDK)

makes me think it would be probably faster and simpler (and more beneficial for the Rust SDK) to implement such secure techniques, rather than going on the path to an external storage implementation API.

Moreover, it opens doors to code we cannot review (not from you specifically, but from other users out there), and so to behaviors we cannot ensure, or to guarantees we cannot hold.

I see multiple arguments that are not in favor of going that path, hence I would prefer to discuss the Why of this feature request at first :-). Maybe that's something you've already done, and the only solution would be this external storage API, but I would like to validate this first please :-).

**Comment by Hywan** [comment]
As discussed in meetings, this feature is no longer required. Closing it. Feel free to re-open if you believe it's still required for something else.
